version: 2.1
jobs:
  chromatic-deployment:
    docker:
      - image: cimg/node:19.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npx chromatic --project-token --project-token=${CHROMATIC_PROJECT_TOKEN}

workflows:
  chromatic-deploy:
    jobs:
      - chromatic-deployment